variable "name" {}
variable "node" {}
variable "vm_size" {}
variable "publisher" {}
variable "offer" {}
variable "sku" {}
variable "disk_size_gb" {}
variable "managed_disk_type" {}
variable "admin_username" {}
variable "key_data" {}
